FROM tensorflow/tensorflow:latest-gpu

RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
--mount=target=/var/cache/apt,type=cache,sharing=locked \
rm -f /etc/apt/apt.conf.d/docker-clean && \
apt-get update && \
apt-get install ffmpeg libsm6 libxext6 libcairo2 libcairo2-dev -y

ADD ./requirements.gpu.txt .
RUN /usr/bin/python3 -m pip install --upgrade pip && \
pip install -r requirements.gpu.txt

ADD . .

ENTRYPOINT [ "flask", "--app", "hairstyler", "run", "--cert=certificates/cert.pem", "--key=certificates/key.pem", "--host=0.0.0.0" ]
